### ISSUE TITLE
Package not importable

### ISSUE THREAD

**Issue by pnegahdar** [samber/go-gpt-3-encoder#1]
Just a heads up that this package is not importable as is. 

```
go: github.com/samber/go-gpt-3-encoder@v0.1.0: parsing go.mod:
        module declares its path as: gpt-3-encoder
                but was required as: github.com/samber/go-gpt-3-encoder

```

This would require changing the module name in the go.mod to be `github.com/samber/go-gpt-3-encoder`

**Comment by timestee** [comment]
> Just a heads up that this package is not importable as is.
> 
> ```
> go: github.com/samber/go-gpt-3-encoder@v0.1.0: parsing go.mod:
>         module declares its path as: gpt-3-encoder
>                 but was required as: github.com/samber/go-gpt-3-encoder
> ```
> 
> This would require changing the module name in the go.mod to be `github.com/samber/go-gpt-3-encoder`

can not wait anymore , so [fored](https://github.com/sandwich-go/gpt3-encoder)

**Comment by samber** [comment]
Thanks for the feedback!
